version: '3'
services:
  backend: &backend
    build:
      context: .
    image: backend
    user: root
    depends_on:
      - postgresql
    volumes:
      - .:/app/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    entrypoint:
      - invoke
      - wait-for
      - postgresql:5432
      - migrate
      - runserver
      - --debug
  postgresql:
    image: postgres:14-alpine3.14
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  rabbitmq:
    image: 'rabbitmq:3.9.9-alpine'
    ports:
      - 5672:5672
  celeryworker:
    <<: *backend
    image: celery:local
    ports: [ ]
    depends_on:
      - postgresql
      - rabbitmq
    entrypoint:
      - invoke
      - wait-for
      - rabbitmq:5672
      - wait-for
      - postgresql:5432
      - celery-queues
  celery-beat:
    <<: *backend
    image: celery-beat
    depends_on:
      - postgresql
      - rabbitmq
    ports: [ ]
    entrypoint:
      - invoke
      - wait-for
      - rabbitmq:5672
      - wait-for
      - postgresql:5432
      - celery-beat
  flower:
    <<: *backend
    ports:
      - 5555:5555
    depends_on:
      - postgresql
      - rabbitmq
    entrypoint:
      - invoke
      - wait-for
      - rabbitmq:5672
      - wait-for
      - postgresql:5432
      - flower
volumes:
  postgres_data: